### ISSUE TITLE
IllegalArgumentException when using with Brave Tracer

### ISSUE THREAD

**Issue by michbeck100** [opentracing-contrib/java-api-extensions#16]
When using the extensions with brave-opentracing I'm getting an IllegalArgumentException when  APIExtensionsSpanBuilder#startActive is called:

```
java.lang.IllegalArgumentException: Span must be an instance of brave.opentracing.BraveSpan, but was class io.opentracing.contrib.api.tracer.APIExtensionsSpan
	at brave.opentracing.BraveScopeManager.activate(BraveScopeManager.java:75) ~[brave-opentracing-0.31.1.jar:na]
	at brave.opentracing.BraveScopeManager.activate(BraveScopeManager.java:26) ~[brave-opentracing-0.31.1.jar:na]
	at io.opentracing.contrib.api.tracer.APIExtensionsSpanBuilder.startActive(APIExtensionsSpanBuilder.java:120) ~[opentracing-api-extensions-tracer-0.1.0.jar:na]
	at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:156) ~[opentracing-web-servlet-filter-0.1.0.jar:na]
```

To fix this the BraveScopeManager should be called with the original span instead of the APIExtensionsSpan version.

**Comment by objectiser** [comment]
Unfortunately this is not possible, as the library needs to register the `APIExtensionsSpan` instance with the `ScopeManager`, rather than the `BraveSpan`, as the wrapper intercepts various method calls on the span to then invoke the `SpanObserver`.

For example, instrumentation may later retrieve the active span from the `ScopeManager` to add tags, logs or finish the span. These must be performed on the `APIExtensionsSpan` instance, otherwise the observer would not be called.

**Comment by objectiser** [comment]
I'm going to close the issue, but feel free to re-open if you would like to discuss further. Other option would be to raise an issue against the OT spec to start a discussion about supporting the observer as part of the core API.

**Comment by michbeck100** [comment]
Another option to implement the extensions would be to use a proxy using java.lang.reflect.Proxy. This would solve the problem with class casts.
Did you think about this option when implementing?

**Comment by sjoerdtalsma** [comment]
@michbeck100 Using proxies could actually be a really good idea.  
One possibly complicating factor that must be considered is the new module system introduced by Java 9. Switching to proxies may make modularizing the api-extensions in the future more difficult.

**Comment by objectiser** [comment]
@michbeck100 no didn't consider this option at the time, but as @sjoerdtalsma says, could be a good idea.

Would you be interested in contributing a PR, and also possibly looking into the java9 issue mentioned by @sjoerdtalsma ?

**Comment by whiskeysierra** [comment]
> Another option to implement the extensions would be to use a proxy using java.lang.reflect.Proxy. This would solve the problem with class casts.

Java Proxies only support interfaces, not classes and BraveSpan is a class. I don't believe this would work.

What might work is to keep references to spans in weak-reference, identity hashmap which maps real span to instrumented span. Before passing something to the underlying implementation you unwrap it and when we get an uninstrumented span back that we need to expose we look it up in that map.

**Comment by whiskeysierra** [comment]
On a second thought, why not have a proxy for `ScopeManager` which automatically decorates any span it exposes via `activeSpan`?

**Comment by objectiser** [comment]
@whiskeysierra How would the proxied `ScopeManager` be set on the tracer?

**Comment by whiskeysierra** [comment]
You just return it upon every call to the scopeManager method.
